// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("LogEater.Wpf")]
[assembly: AssemblyProductAttribute("LogEater")]
[assembly: AssemblyDescriptionAttribute("A simple log file viewer")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
